### ISSUE TITLE
encfs: Osxfuse Requirement unsatisfied!

### ISSUE THREAD

**Issue by todd-dsm** [todd-dsm/mac-ops#25]
```
encfs: OsxfuseRequirement unsatisfied!
You can install with Homebrew-Cask:
 brew cask install osxfuse
You can download from:
 https://osxfuse.github.io/
Error: An unsatisfied requirement failed this build.
```

---
moved gnupg down to after the osxfuse install

**Comment by todd-dsm** [comment]
installed `gnupg` after `osxfuse`; no issues.

**Comment by justOleh** [comment]
It seams to meet we just need to install osxfuse. Following tip from brew, you should brew install --cask osxfuse. It fixed error for me.

**Comment by mobiusint** [comment]
doesn't seem to work for me mac os 11.6.8
